import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.scss";
import styles from '../page.module.scss'
const openSans = Open_Sans({
  subsets: ["latin","cyrillic"],
})


export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

//корневой документ
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.className}`}>
      Корневой layout проекта
      <nav className={styles.nav}>
          <ul>
              <li>Курсы</li>
              <li>Для детей</li>
              <li>О нас</li>
          </ul>
      </nav>
        {children}
      </body>
    </html>
  );
}
