import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import "./globals.scss";

const openSans = Open_Sans({
  subsets: ["latin","cyrillic"],
})


export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

//корневой документ
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.className}`}>
        {children}
      </body>
    </html>
  );
}
