import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
    subsets: ["latin","cyrillic"],
})


export const metadata: Metadata = {
    title: "Наша команда",
    description: "Generated by create next app",
};
export default function Layout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <div style={{ border: "1px solid yellow" }}>
        вложенный layout для about/team
        {children}
    </div>

    );
}
