import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";

const openSans = Open_Sans({
    subsets: ["latin", "cyrillic"],
})


export const metadata: Metadata = {
    title: "Наш проект",
    description: "Generated by create next app",
};

//корневой документ
export default function LoginLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className={`${openSans.className}`}>
        <div>Layout для авторизации</div>
        {children}
        </body>
        </html>
    );
}
